# prompts.yaml
prompts:
  customer_service:
    system: "你是一名专业的客服代表"
    template: |
      请用友好、专业的语气回答用户问题。
      用户问题: {question}
      公司信息: {company_info}
      历史对话: {history}
      请根据以上信息提供帮助:
    parameters:
      - question
      - company_info
      - history
    metadata:
      version: "1.2"
      author: "AI团队"
      created: "2024-01-01"
  
  data_analysis:
    system: "你是一名数据分析师"
    template: |
      请分析以下数据并给出洞察。
      数据摘要: {data_summary}
      分析要求: {requirement}
      请提供详细分析:
    parameters:
      - data_summary
      - requirement
  
  meeting_summary:
    system: "你是一名专业的会议记录员"
    template: |
      请根据以下会议录音转录内容生成会议摘要。
      
      会议转录内容:
      {transcript}

      额外背景信息：{context}
      
      请生成一个结构化的会议摘要，包括：
      1. 主要讨论议题
      2. 关键决策和结论
      3. 行动项和责任人员（如果提到）
      4. 下次会议安排（如果有）
      5. 其他重要事项
    parameters:
      - transcript
      - context
  
  meeting_minutes:
    system: "你是一名专业的会议记录员"
    template: |
      请根据以下会议录音转录内容生成详细的会议纪要。
      
      会议主题: {meeting_topic}
      参会人员: {attendees}
      
      会议转录内容:
      {transcript}
      
      
      请生成包含以下结构的详细会议纪要：
      1. 会议基本信息（主题、时间、参会人员）
      2. 主要讨论议题
      3. 关键决策和结论
      4. 行动项和责任人员
      5. 下次会议安排
      6. 备注事项
    parameters:
      - meeting_topic
      - attendees
      - transcript

  meeting_key_points:
    system: "你是一名专业的会议记录员"
    template: |
        请从以下会议录音转录中提取关键要点，每条要点以"-"开头。

        会议转录内容：
        {transcript}

        请提取5-10个关键要点：
    parameters:
      - transcript

  meeting_technical_term_explanation:
    system: "你是一名专业的会议记录员"
    template: |
        请从以下会议录音转录中识别并解释所有专有名词。

        会议转录内容：
        {transcript}

        请列出较难理解的专有名词及其简要解释,必要时提供示例便于理解。格式为“-key:value”：
    parameters:
      - transcript